- name: Run the database container
  docker_container:
    name: my-db
    image: loiccassan/database  
    networks:
      - name: my-network
    volumes:
      - db-volume:/var/lib/postgresql/data
    state: started
    restart_policy: always
